
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model Tenant
 * Organization/Team - the top-level tenant entity
 */
export type Tenant = Prisma.TenantModel
/**
 * Model User
 * User belongs to exactly one tenant
 */
export type User = Prisma.UserModel
/**
 * Model Group
 * Groups for organizing users within a tenant
 */
export type Group = Prisma.GroupModel
/**
 * Model Role
 * Role-based access control within a tenant
 */
export type Role = Prisma.RoleModel
/**
 * Model Invite
 * Invitations for users to join a tenant
 */
export type Invite = Prisma.InviteModel
/**
 * Model Board
 * Board / Project within a tenant
 */
export type Board = Prisma.BoardModel
/**
 * Model Task
 * Task / Todo item within a board
 */
export type Task = Prisma.TaskModel
/**
 * Model RefreshToken
 * Refresh tokens for JWT authentication
 */
export type RefreshToken = Prisma.RefreshTokenModel
