
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import * as $Class from "./internal/class.js"
import * as Prisma from "./internal/prismaNamespace.js"

export * as $Enums from './enums.js'
export * from "./enums.js"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Tenants
 * const tenants = await prisma.tenant.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model Tenant
 * Organization/Team - the top-level tenant entity
 */
export type Tenant = Prisma.TenantModel
/**
 * Model User
 * User belongs to exactly one tenant
 */
export type User = Prisma.UserModel
/**
 * Model Group
 * Groups for organizing users within a tenant
 */
export type Group = Prisma.GroupModel
/**
 * Model Role
 * Role-based access control within a tenant
 */
export type Role = Prisma.RoleModel
/**
 * Model Board
 * Board / Project within a tenant
 */
export type Board = Prisma.BoardModel
/**
 * Model Task
 * Task / Todo item within a board
 */
export type Task = Prisma.TaskModel
/**
 * Model RefreshToken
 * Refresh tokens for JWT authentication
 */
export type RefreshToken = Prisma.RefreshTokenModel
